namespace: default
image: cyborch/corp:1.1.0

virtualHosts:
  - hostname: proxy.example.com
    scheme: http
    origin: https://google.com
    enableCors: true
    skipHeaders:
      - X-Frame-Options
